{"name": "test_login2", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 2", "trace": "self = <test_login.TestLogin object at 0x0000026EFF1973D0>\n\n    @pytest.mark.system\n    def test_login2(self):\n>       assert 1 == 2\nE       assert 1 == 2\n\ntest_case\\test_login\\test_login.py:35: AssertionError"}, "start": 1649225636625, "stop": 1649225636625, "uuid": "1ae745eb-9982-44df-8364-c3d4b8400961", "historyId": "b2732eef22232c85ab25009b2a56b184", "testCaseId": "f2900759f27a48071b98cae5093c1b7a", "fullName": "test_case.test_login.test_login.TestLogin#test_login2", "labels": [{"name": "tag", "value": "system"}, {"name": "parentSuite", "value": "test_case.test_login"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-8LS2KV9"}, {"name": "thread", "value": "27384-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case.test_login.test_login"}]}