{"name": "test_login2", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 2", "trace": "self = <test_login.TestLogin object at 0x000002061A1FB670>\n\n    @pytest.mark.system\n    def test_login2(self):\n>       assert 1 == 2\nE       assert 1 == 2\n\ntest_case\\test_login\\test_login.py:35: AssertionError"}, "start": 1649227162852, "stop": 1649227162852, "uuid": "4ba3ffa7-b602-42a4-acb4-0a7ce2988ef6", "historyId": "b2732eef22232c85ab25009b2a56b184", "testCaseId": "f2900759f27a48071b98cae5093c1b7a", "fullName": "test_case.test_login.test_login.TestLogin#test_login2", "labels": [{"name": "tag", "value": "system"}, {"name": "parentSuite", "value": "test_case.test_login"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-8LS2KV9"}, {"name": "thread", "value": "22716-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case.test_login.test_login"}]}