{"name": "test_login4", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 2", "trace": "self = <test_login.TestLogin object at 0x000001C46A0DED90>\n\n    @pytest.mark.system\n    def test_login4(self):\n>       assert 1 == 2\nE       assert 1 == 2\n\ntest_case\\test_login\\test_login.py:35: AssertionError"}, "start": 1649227216025, "stop": 1649227216025, "uuid": "880a02a9-d4b1-42dd-a87b-4052bf8b7712", "historyId": "0901adacca7ae0dbb61202c478bc3a0f", "testCaseId": "cd9efd51cfdcd7b9367073cf064589cc", "fullName": "test_case.test_login.test_login.TestLogin#test_login4", "labels": [{"name": "tag", "value": "system"}, {"name": "parentSuite", "value": "test_case.test_login"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-8LS2KV9"}, {"name": "thread", "value": "21444-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case.test_login.test_login"}]}