{"name": "test_login3", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 2", "trace": "self = <test_login.TestLogin object at 0x000001D5F2191910>\n\n    @pytest.mark.login\n    def test_login3(self):\n>       assert 1 == 2\nE       assert 1 == 2\n\ntest_case\\test_login\\test_login.py:31: AssertionError"}, "start": 1649225658005, "stop": 1649225658005, "uuid": "14ba7c05-d0f5-45d7-a0bf-5bb54d47f423", "historyId": "10403f71c9092af0ae5d356fc7dace05", "testCaseId": "fab37a754f6769b12ccad774e7c454fa", "fullName": "test_case.test_login.test_login.TestLogin#test_login3", "labels": [{"name": "tag", "value": "login"}, {"name": "parentSuite", "value": "test_case.test_login"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-8LS2KV9"}, {"name": "thread", "value": "24200-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case.test_login.test_login"}]}