{"name": "test_login3", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 2", "trace": "self = <test_login.TestLogin object at 0x000001C46A0DEBE0>\n\n    @pytest.mark.login\n    def test_login3(self):\n>       assert 1 == 2\nE       assert 1 == 2\n\ntest_case\\test_login\\test_login.py:31: AssertionError"}, "start": 1649227215795, "stop": 1649227215795, "uuid": "4da0abc9-c521-41ed-87a8-1a76037b77e2", "historyId": "10403f71c9092af0ae5d356fc7dace05", "testCaseId": "fab37a754f6769b12ccad774e7c454fa", "fullName": "test_case.test_login.test_login.TestLogin#test_login3", "labels": [{"name": "tag", "value": "login"}, {"name": "parentSuite", "value": "test_case.test_login"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-8LS2KV9"}, {"name": "thread", "value": "21444-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case.test_login.test_login"}]}